(() => {
    const { REALMS, CURRENCY_LABEL, SPIRITS, ELDERS, SEASON_PRESETS } = window.SKY_DATA;
    const STORAGE_KEY = 'sky-spirit-tracker-v3';
    const app = document.querySelector('#app');
    const state = loadState();
    state.tab = 'regular';
    state.open = new Set();
    state.hideDone = false;

    function loadState() {
        try { return Object.assign({ includeT2: false, nodes: {}, elders: {}, seasonal: [] }, JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}')); }
        catch { return { includeT2: false, nodes: {}, elders: {}, seasonal: [] }; }
    }
    function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify({ includeT2: state.includeT2, nodes: state.nodes, elders: state.elders, seasonal: state.seasonal })); }
    function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
    function visibleStages(spirit) { return spirit.stages.filter((stage) => state.includeT2 || !stage.t2); }
    function visibleNodes(spirit) { return visibleStages(spirit).flatMap((stage) => stage.nodes); }
    function costOf(nodes) { return nodes.reduce((out, node) => { if (node.cost > 0) out[node.currency] += node.cost; return out; }, { candle: 0, heart: 0, ac: 0 }); }
    function addCost(a, b) { return { candle: a.candle + b.candle, heart: a.heart + b.heart, ac: a.ac + b.ac }; }
    function remaining(spirit) { const done = new Set(state.nodes[spirit.id] || []); return costOf(visibleNodes(spirit).filter((node) => !done.has(node.id))); }
    function progress(spirit) { const list = visibleNodes(spirit).filter((node) => node.cost > 0 || node.label.length); const done = new Set(state.nodes[spirit.id] || []); return { done: list.filter((node) => done.has(node.id)).length, total: list.length }; }
    function progressPercent(value) { return value.total ? Math.round(value.done / value.total * 100) : 0; }
    function currency(key, value) { const symbols = { candle: '🔥', heart: '♥', ac: '★' }; return `<span class="currency ${key}">${symbols[key]} ${value}</span>`; }
    function costHtml(cost, compact = false) { return `<span class="cost ${compact ? 'compact' : ''}">${currency('candle', cost.candle)} ${currency('heart', cost.heart)} ${currency('ac', cost.ac)}</span>`; }
    function button(text, cls = 'button') { return `<button class="${cls}" type="submit">${text}</button>`; }

    function summary() {
        const overall = SPIRITS.reduce((out, spirit) => { const value = progress(spirit); out.done += value.done; out.total += value.total; return out; }, { done: 0, total: 0 });
        const regular = SPIRITS.reduce((out, spirit) => addCost(out, remaining(spirit)), { candle: 0, heart: 0, ac: 0 });
        const elderAc = ELDERS.reduce((sum, elder) => sum + (state.elders[elder.id] ? 0 : elder.ac), 0);
        const seasonal = state.seasonal.reduce((out, spirit) => addCost(out, costOf(visibleNodes(spirit).filter((node) => !(state.nodes[spirit.id] || []).includes(node.id)))), { candle: 0, heart: 0, ac: 0 });
        return `<section class="summary"><div class="panel"><p class="label">恒常 残り</p><div class="summary-value">${costHtml(regular)}</div></div><div class="panel"><p class="label">大精霊 残り</p><p class="summary-value currency ac">★ ${elderAc}</p></div><div class="panel"><p class="label">季節 残り</p><div class="summary-value">${costHtml(seasonal)}</div></div><div class="panel"><p class="label">星キャンドル合計</p><p class="summary-value currency ac">${regular.ac + elderAc + seasonal.ac}</p></div><div class="panel progress-panel"><p class="label">恒常精霊 全体の進捗</p><div class="progress-meta"><strong>${progressPercent(overall)}%</strong><span>${overall.done}/${overall.total} 項目</span></div><div class="progress-track"><span style="width:${progressPercent(overall)}%"></span></div></div></section>`;
    }
    function nodeHtml(spiritId, node) { const done = (state.nodes[spiritId] || []).includes(node.id); const right = node.cost === 0 ? '<span class="subtle">無料</span>' : currency(node.currency, node.cost); return `<button type="button" class="node-row ${done ? 'done' : ''}" data-action="toggle-node" data-spirit="${spiritId}" data-node="${node.id}"><span class="check ${done ? 'done' : ''}">${done ? '✓' : ''}</span><span class="grow node-label">${escapeHtml(node.label)}</span>${node.grantsHeart ? '<span class="subtle currency heart">入手 +1</span>' : ''}${right}</button>`; }
    function stageHtml(spirit, stage) { const done = new Set(state.nodes[spirit.id] || []); const allDone = stage.nodes.every((node) => done.has(node.id)); const leftover = costOf(stage.nodes.filter((node) => !done.has(node.id))); return `<div class="stage"><div class="stage-head"><span class="stage-name">${escapeHtml(stage.label)}</span><span>${allDone ? '<span class="currency ac">完了</span>' : costHtml(leftover, true)} <button type="button" class="stage-action" data-action="stage" data-spirit="${spirit.id}" data-stage="${stage.id}" data-done="${!allDone}">${allDone ? '解除' : 'この段階を完了'}</button></span></div>${stage.nodes.map((node) => nodeHtml(spirit.id, node)).join('')}</div>`; }
    function spiritHtml(spirit) { const p = progress(spirit); const allDone = p.total > 0 && p.done === p.total; const pct = p.total ? Math.round(p.done / p.total * 100) : 0; const open = state.open.has(spirit.id); return `<article class="card ${open ? 'open' : ''}"><button type="button" class="card-toggle" data-action="spirit" data-spirit="${spirit.id}"><span class="percent">${pct}</span><span class="grow"><strong class="truncate">${escapeHtml(spirit.name)}</strong><span class="subtle">${p.done}/${p.total} 項目</span></span>${costHtml(remaining(spirit), true)}<span class="chevron">⌄</span></button>${open ? `<div class="card-body"><div class="row-head"><span></span><button type="button" class="text-button" data-action="spirit-all" data-spirit="${spirit.id}" data-done="${!allDone}">${allDone ? 'この精霊を未完了に' : '表示中の全段階を完了'}</button></div>${visibleStages(spirit).map((stage) => stageHtml(spirit, stage)).join('')}</div>` : ''}</article>`; }
    function regularPanel() { return `<div class="toolbar"><button type="button" class="pill ${!state.includeT2 ? 'active' : ''}" data-action="t2" data-value="false">星座100%</button><button type="button" class="pill ${state.includeT2 ? 'active' : ''}" data-action="t2" data-value="true">全交換・T2込</button><button type="button" class="pill ${state.hideDone ? 'active' : ''}" data-action="hide">未完了のみ</button></div><div class="stack">${REALMS.map((realm) => { const realmSpirits = SPIRITS.filter((s) => s.realm === realm.id); const list = realmSpirits.filter((s) => !state.hideDone || progress(s).done < progress(s).total); if (!list.length) return ''; const total = list.reduce((out, s) => addCost(out, remaining(s)), { candle: 0, heart: 0, ac: 0 }); const realmProgress = realmSpirits.reduce((out, spirit) => { const value = progress(spirit); out.done += value.done; out.total += value.total; return out; }, { done: 0, total: 0 }); return `<section class="realm"><div class="realm-head"><h2>${escapeHtml(realm.name)}</h2><div class="realm-progress"><strong>${progressPercent(realmProgress)}%</strong><span>${realmProgress.done}/${realmProgress.total} 項目</span>${costHtml(total, true)}</div></div>${list.map(spiritHtml).join('')}</section>`; }).join('')}</div>`; }
    function eldersPanel() { return `<div class="stack"><p class="hint">星座100%のあと、原罪をクリアして天空で大精霊と交換します。項目ごとに記録できます。</p>${REALMS.map((realm) => { const list = ELDERS.filter((elder) => elder.realm === realm.id); if (!list.length) return ''; return `<section class="card"><h2 class="stage-head">${escapeHtml(realm.name)}</h2>${list.map((elder) => { const done = !!state.elders[elder.id]; return `<button type="button" class="elder-row ${done ? 'done' : ''}" data-action="elder" data-elder="${elder.id}"><span class="check ${done ? 'done' : ''}">${done ? '✓' : ''}</span><span class="grow ${done ? 'subtle' : ''}">${escapeHtml(elder.name)}</span>${currency('ac', elder.ac)}</button>`; }).join('')}</section>`; }).join('')}</div>`; }
    function seasonalPanel() { return `<div class="stack"><p class="hint">再訪精霊はコストが変わるため、段階（ノード）を自分で追加してチェックします。</p><section class="panel" style="padding:16px"><h3>精霊を追加</h3><form class="form-grid season-form" data-form="spirit"><input name="name" placeholder="精霊名" required><select name="season">${SEASON_PRESETS.map((season) => `<option>${escapeHtml(season)}</option>`).join('')}</select>${button('＋ 追加', 'button primary')}</form></section>${state.seasonal.length ? state.seasonal.map(seasonHtml).join('') : '<p class="empty">まだ季節精霊はありません。</p>'}</div>`; }
    function seasonHtml(spirit) { const nodes = spirit.stages.flatMap((stage) => stage.nodes); return `<article class="season-card"><div class="season-meta"><div><h3>${escapeHtml(spirit.name)}</h3><p class="subtle">${escapeHtml(spirit.season)}</p></div><button type="button" class="icon-button" data-action="remove-season" data-spirit="${spirit.id}" aria-label="削除">×</button></div><div>${nodes.map((node) => `<div class="row-head"><span class="grow">${nodeHtml(spirit.id, node)}</span><button type="button" class="icon-button" data-action="remove-node" data-spirit="${spirit.id}" data-node="${node.id}" aria-label="項目を削除">×</button></div>`).join('')}</div><form class="form-grid" data-form="node" data-spirit="${spirit.id}"><input name="label" placeholder="項目名（例: ケープ）" required><select name="currency">${Object.entries(CURRENCY_LABEL).map(([key, label]) => `<option value="${key}">${label}</option>`).join('')}</select><div style="display:flex;gap:8px"><input name="cost" type="number" min="0" value="1" inputmode="numeric"><button class="button primary" type="submit" aria-label="項目追加">＋</button></div></form></article>`; }
    function dataPanel() { const data = JSON.stringify({ nodes: state.nodes, elders: state.elders, seasonal: state.seasonal, includeT2: state.includeT2 }, null, 2); return `<div class="stack"><div class="toolbar"><button type="button" class="button primary" data-action="export">↓ 書き出し</button><label class="button"><input class="hidden" type="file" accept="application/json" data-action="import">↑ 読み込み</label><button type="button" class="button danger" data-action="reset">↻ リセット</button></div><p class="hint">記録はこの端末のブラウザに保存されます。書き出したJSONを保管すれば別端末でも復元できます。</p><pre>${escapeHtml(data)}</pre></div>`; }
    function render() { const panels = { regular: regularPanel, elders: eldersPanel, seasonal: seasonalPanel, data: dataPanel }; app.innerHTML = `<header><p class="eyebrow">SKY CHILDREN OF THE LIGHT</p><h1>精霊交換帳</h1><p class="lede">友情ツリーを段階ごとに記録し、残りキャンドル・ハート・星キャンドルを集計します。</p></header>${summary()}<nav class="tabs-wrap"><div class="tabs">${[['regular', '恒常精霊'], ['elders', '大精霊'], ['seasonal', '季節精霊'], ['data', 'データ']].map(([id, label]) => `<button type="button" class="tab ${state.tab === id ? 'active' : ''}" data-action="tab" data-tab="${id}">${label}</button>`).join('')}</div></nav><section>${panels[state.tab]()}</section>`; }
    function idsFor(spirit, includeT2) { return spirit.stages.filter((stage) => includeT2 || !stage.t2).flatMap((stage) => stage.nodes.map((node) => node.id)); }
    function toggleNode(spiritId, nodeId) { const ids = new Set(state.nodes[spiritId] || []); ids.has(nodeId) ? ids.delete(nodeId) : ids.add(nodeId); state.nodes[spiritId] = [...ids]; }
    app.addEventListener('click', (event) => { const target = event.target.closest('[data-action]'); if (!target) return; const action = target.dataset.action; if (action === 'tab') state.tab = target.dataset.tab; if (action === 't2') state.includeT2 = target.dataset.value === 'true'; if (action === 'hide') state.hideDone = !state.hideDone; if (action === 'spirit') state.open.has(target.dataset.spirit) ? state.open.delete(target.dataset.spirit) : state.open.add(target.dataset.spirit); if (action === 'toggle-node') toggleNode(target.dataset.spirit, target.dataset.node); if (action === 'stage' || action === 'spirit-all') { const spirit = SPIRITS.find((item) => item.id === target.dataset.spirit); const ids = action === 'stage' ? (spirit.stages.find((stage) => stage.id === target.dataset.stage)?.nodes || []).map((node) => node.id) : idsFor(spirit, state.includeT2); const completed = new Set(state.nodes[spirit.id] || []); ids.forEach((id) => target.dataset.done === 'true' ? completed.add(id) : completed.delete(id)); state.nodes[spirit.id] = [...completed]; } if (action === 'elder') state.elders[target.dataset.elder] = !state.elders[target.dataset.elder]; if (action === 'remove-season') { state.seasonal = state.seasonal.filter((item) => item.id !== target.dataset.spirit); delete state.nodes[target.dataset.spirit]; } if (action === 'remove-node') { const spirit = state.seasonal.find((item) => item.id === target.dataset.spirit); spirit.stages.forEach((stage) => { stage.nodes = stage.nodes.filter((node) => node.id !== target.dataset.node); }); delete state.nodes[target.dataset.spirit]; } if (action === 'export') exportData(); if (action === 'reset' && confirm('すべての交換記録を消しますか？')) { state.nodes = {}; state.elders = {}; state.seasonal = []; } save(); render(); });
    app.addEventListener('submit', (event) => { event.preventDefault(); const form = event.target; const data = new FormData(form); if (form.dataset.form === 'spirit') { const id = `seasonal_${Date.now().toString(36)}`; state.seasonal.push({ id, name: String(data.get('name')).trim(), season: data.get('season'), stages: [{ id: `${id}__s1`, label: '段階1', nodes: [] }] }); } else { const spirit = state.seasonal.find((item) => item.id === form.dataset.spirit); if (spirit && String(data.get('label')).trim()) spirit.stages[0].nodes.push({ id: `${spirit.id}__n_${Date.now().toString(36)}`, label: String(data.get('label')).trim(), currency: data.get('currency'), cost: Number(data.get('cost')) || 0 }); } save(); render(); });
    app.addEventListener('change', (event) => { if (event.target.dataset.action !== 'import') return; const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const imported = JSON.parse(reader.result); Object.assign(state, { nodes: imported.nodes || {}, elders: imported.elders || {}, seasonal: imported.seasonal || [], includeT2: imported.includeT2 || false }); save(); render(); } catch { alert('JSONを読み込めませんでした。'); } }; reader.readAsText(file); });
    function exportData() { const blob = new Blob([JSON.stringify({ nodes: state.nodes, elders: state.elders, seasonal: state.seasonal, includeT2: state.includeT2 }, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `sky-tracker-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(link.href); }
    render();
})();
